basic_settings:
  site_title: paiva
  favicon_image: /images/favicon.ico

header_settings:
  logo_image:
  logo_width: 100

menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Blog"
      url: "/blog/"
    - title: "Resume"
      url: "/resume"
    - title: "References"
      url: "/references"

footer_settings:
  logo_image:
  logo_width: 100
  tagline: Marcelo Paiva = UX + DEV + Accessibility

hero_settings:
  background_image: /images/backgrounds/background-hero.svg

projects_settings:
  projects_title: Recent Projects
  projects_description: "The following are some of my latest work available to be displayed publicly. Confidential material available to be glanced upon request."

post_settings:
  grid_spacing: 10

contact_settings:
  email_address: "mpaiva@gmail.com"
  form_action: "https://formspree.io/f/mayzdeyk"
  confirmation_url: "/thanks"
  email_subject: "Venus Inquiry"
  send_button_text: "Get in Touch"

#-------------------------------

# About Random Images
about_settings:
  - image: /images/about/diversity_picasso.png
    alt: "A generative art created using MidJourney, where it illustrates a diverse group of people using Pablo Picasso's painting style."
    caption: "I pledge to design for All users, regardless of race, ethnicity, age, gender, religion, sexual orientation, gender identity, gender expression, disability, economic status and other diverse backgrounds."
    prompt: "a group of people from different race, ethnicity, age, gender, religion, disability, economic status and other diverse backgrounds, on a white background, Pablo Picasso style. --v 5 --s 250"

  - image: /images/about/diversity_rockwell.png
    alt: "A generative art created using MidJourney, where it illustrates a diverse group of people using Norman Rockwell's painting style."
    caption: "I pledge to design for All users, regardless of race, ethnicity, age, gender, religion, sexual orientation, gender identity, gender expression, disability, economic status and other diverse backgrounds."
    prompt: "a group of people from different race, ethnicity, age, gender, religion, disability, economic status and other diverse backgrounds, on a white background, Norman Rockwell style. --v 5 --s 250"

  - image: /images/about/diversity_whitmore.png
    alt: "A generative art created using MidJourney, where it illustrates a diverse group of people using Coby Whitmore's painting style."
    caption: "I pledge to design for All users, regardless of race, ethnicity, age, gender, religion, sexual orientation, gender identity, gender expression, disability, economic status and other diverse backgrounds."
    prompt: "a group of people from different race, ethnicity, age, gender, religion, disability, economic status and other diverse backgrounds, on a white background, Coby Whitmore style. --v 5 --s 250"

  - image: /images/about/diversity_yoshitaka_amano.png
    alt: "A generative art created using MidJourney, where it illustrates a diverse group of people using Yoshitaka Amano's painting style."
    caption: "I pledge to design for All users, regardless of race, ethnicity, age, gender, religion, sexual orientation, gender identity, gender expression, disability, economic status and other diverse backgrounds."
    prompt: "a group of people from different race, ethnicity, age, gender, religion, disability, economic status and other diverse backgrounds, on a white background, Yoshitaka Amano style. --v 5 --s 250"

  - image: /images/about/diversity_neal_adams.png
    alt: "A generative art created using MidJourney, where it illustrates a diverse group of people using Neal Adams's painting style."
    caption: "I pledge to design for All users, regardless of race, ethnicity, age, gender, religion, sexual orientation, gender identity, gender expression, disability, economic status and other diverse backgrounds."
    prompt: "a group of people from different race, ethnicity, age, gender, religion, disability, economic status and other diverse backgrounds, on a white background, Neal Adams style. --v 5 --s 250"

# Testimonials Section
testimonials:
  enable: true

testimonial__title: Testimonials
testimonial__description: Leadership changes frequently, but team members are forever and genuine.

testimonial__items:
  - name: "Colleen Stafford"
    company: "UKG"
    image: "cstafford.jpeg"
    role: "Lead Designer"
    link: "https://www.linkedin.com/in/colleenstafford/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

  - name: "Lorem Mack"
    company: "UKG"
    image: "lmack.jpeg"
    role: "Principal Designer"
    link: "https://www.linkedin.com/in/lorenmack/"
    content: "Marcelo is by an order of magnitude one of the best managers that's ever worked for me.  Yes, you read that right - he works *for* his direct reports. He embodies all of the best traits in a 'servant leader'."

  - name: "Shaun Pansolli"
    company: "UKG"
    image: "spansolli.jpeg"
    role: "Lead Designer"
    link: "https://www.linkedin.com/in/shaun-pansolli-20039626/"
    content: "Marcelo is an outstanding UX leader, teacher and one of the most genuine people I have worked with. He is an advocate and leader for accessibility and inclusiveness in UX and Design thinking methodologies."

  - name: "Lauren Schaefer"
    company: "South Florida UX"
    image: "lschaefer.jpeg"
    role: "UX Community Leader"
    link: "https://www.linkedin.com/in/laurenemartin/"
    content: "An invaluable partner to me in running the South Florida UX community networking and partnerships events. A brilliant contributor who is invested in the community, helping others, and creating products that lift people up through thoughtful and universal design."

  - name: "Marta Guerra"
    company: "Amazon"
    image: "mguerra.jpeg"
    role: "Sr. UX Designer, Author"
    link: "https://www.linkedin.com/in/guerramarta/"
    content: "Marcelo is brilliant UX Designer and educator that I had the opportunity to work at UKG. A visionary, expert in Design Systems, and accessibility guru."

  - name: "Richard Novoa"
    company: "NFI"
    image: "rnovoa.jpeg"
    role: "UX Designer"
    link: "https://www.linkedin.com/in/novoadesign/"
    content: "Leader, mentor and educator, I have had the honor of being guided by one of the best. His attention to detail and his leadership style inspires you to craft products users will love, by intent and not by luck. Marcelo genuinely takes interest in the betterment of others, the creation of communities and the inclusivity of all users."

  - name: "Joel Mena"
    company: "CryptoLeague"
    image: "jmena.jpeg"
    role: "UX Evangelist, Coach and Speaker"
    link: "https://www.linkedin.com/in/joelmena/"
    content: "Marcelo is that rare breed of creative and technical mind. His ability to quickly grasp complex ideas and synthesize them into executable plans is second to none. Marcelo is a natural leader capable of successfully building technical teams and bringing people together around a common goal."

  - name: "Bianka McGovern"
    company: "Amazon"
    image: "bmcgovern.jpeg"
    role: "Product Design Leader"
    link: "https://www.linkedin.com/in/bianka-mcgovern-2027293/"
    content: "Marcelo comes with an impressive skillset. He does user experience design, visual design and front-end coding. His designs are innovative yet down to earth and realistic from a development standpoint. "

social_settings:
  facebook_url: ""
  twitter_url: "https://twitter.com/muqueca"
  instagram_url: ""
  snapchat_url: ""
  youtube_url: ""
  google-plus_url: ""
  vimeo_url: ""
  pinterest_url: ""
  medium_url: ""
  quora_url: ""
  amazon_url: ""
  apple_url: ""
  android_url: ""
  tumblr_url: ""
  dribbble_url: ""
  behance_url: ""
  deviantart_url: ""
  github_url: ""
  reddit_url: ""
  flickr_url: ""
  etsy_url: ""
  kickstarter_url: ""
  soundcloud_url: ""
  spotify_url: ""
  bandcamp_url: ""
  linkedin_url: "https://www.linkedin.com/in/mtpaiva/"

color_settings:
  background_color: "#ffffff"
  background_alt_color: "#f4f5f6"
  text_dark_color: "#202224"
  text_medium_color: "#6C7A89"
  text_light_color: "#595959"
  accent_color: "#4C60E6"
  accent_light: "#d1d6fa"
  border_color: "#ECEDEF"
  error_color: "#D64541"
  focus_color: "#0000ff"

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Rubik:400,500,700|Ubuntu+Mono:400,700|Comic+Neue:300,400" rel="stylesheet">'
  title_font: "Rubik, sans-serif"
  body_font: '"Ubuntu Mono", sans-serif'
  quote_font: '"Comic Neue", sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 30
    medium_size: 40
    large_size: 45
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  h1:
    size: 64
    size_small: 42
    weight: 700
    letter_spacing: -1.5
    letter_spacing_small: -1.2
    line_height: 72
    line_height_small: 48
  h2:
    size: 48
    size_small: 36
    weight: 700
    letter_spacing: -1.6
    letter_spacing_small: -1.04
    line_height: 56
    line_height_small: 44
  h3:
    size: 40
    size_small: 30
    weight: 700
    letter_spacing: -1.4
    letter_spacing_small: -0.54
    line_height: 48
    line_height_small: 36
  h4:
    size: 32
    size_small: 28
    weight: 700
    letter_spacing: -1
    letter_spacing_small: -0.6
    line_height: 36
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  subtitle:
    size: 22
    size_small: 20
    weight_regular: 400
    weight_heavy: 500
    letter_spacing: 0.16
    letter_spacing_small: 0.2
    line_height: 32
    line_height_small: 28
  p:
    size: 18
    size_small: 17
    weight: 400
    letter_spacing: -0.5
    letter_spacing_small: 0
    line_height: 28
  p_small:
    size: 16
    size_small: 15
    weight: 400
    letter_spacing: 0
    line_height: 24
  label:
    size: 14
    small_size: 12
    weight: 500
    letter_spacing: 0.8
    small_letter_spacing: 0.5
    line_height: 16
  footnote:
    size: 13
    weight: 400
    letter_spacing: -0.04
    line_height: 12
  blockquote:
    small_size: 22
    medium_size: 30
    large_size: 38
    weight: 500
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0.4

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
